### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by mirsev** [hapiest-team/hapiest#37]
Sorry, I have never programmed with python, so I have no idea what's wrong...
```
./run
Traceback (most recent call last):
  File "src/__main__.py", line 12, in <module>
    from windows.main_window import *
  File "hapiest/hapiest-master/src/windows/main_window.py", line 15
    self.gui: 'MainWindowGui' = MainWindowGui(self)
            ^
SyntaxError: invalid syntax

```
This is Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] on linux

**Comment by jkarns275** [comment]
You'll need to use python 3.7, as there are type annotations in the code which are not supported by pre 3.7. I'll have to add that to the README.md

**Comment by mirsev** [comment]
Are you sure that this is a good idea to use unreleased Python version for production?

How can I install the latest version of hapiest which still works with python 3.5?

**Comment by jkarns275** [comment]
Oh my apologies - python 3.6 is the requirement, though 3.7 would technically work.

There is no version of hapiest that works with 3.5 because of the type annotations littered throughout the codebase.

**Comment by mirsev** [comment]
OK, found Python 3.6 package for Ubuntu but it seems that something is wrong with the installation...
Any idea?
```
./run
Traceback (most recent call last):
  File "src/__main__.py", line 12, in <module>
    from windows.main_window import *
  File "hapiest/hapiest-master/src/windows/main_window.py", line 4, in <module>
    from utils.isotopologue import *
  File "hapiest/hapiest-master/src/utils/isotopologue.py", line 1, in <module>
    from hapi import *
  File "hapiest/hapiest-master/src/hapi.py", line 26, in <module>
    from numpy import zeros,array,zeros,setdiff1d,ndarray,arange
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
mirsev@qpoint:hapiest-master$ python3.6
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
```

**Comment by jkarns275** [comment]
You probably have to Uninstall numpy for python3.6 and reinstall it. You may have to do that for other dependencies as well.

**Comment by mirsev** [comment]
Thanks for hint. Installed nampy with
`> python3.6 /usr/local/bin/pip install numpy
`
Now I have the GUI... Seems to be working: downloaded data and got plot for CO2.
Thank you.
